### ISSUE TITLE
Unable to use SMTP servers that do NOT require username/password

### ISSUE THREAD

**Issue by TheWebMachine** [salvozappa/pipe-mail#1]
-u and -p are required, precluding use with SMTP servers that are using IP filtering (on a VPN for example) instead of traditional user/pass authentication. 

Are you still able to actively work on this or should we fork and attempt to correct this ourselves? Thanks for any feedback you can provide.

**Comment by salvozappa** [comment]
Hi, at the moment I'm not working on this.

Feel free to send a pull request and I'll happily review it.

Thanks!

**Comment by TheWebMachine** [comment]
Thank you so much for the quick reply! Working on the forked update now. Assuming nodemailer supports those parameters being optionally left out, it should be a pretty easy fix. Your code is so KISS principle compliant; love it! haha

**Comment by TheWebMachine** [comment]
Pull request submitted. I checked nodemailer documentation and there was nothing that indicated that user/pass were explicitly required. In fact, the default auth plugin allows a few conventions, including one where user/pass is not specified because prior authentication was previously obtained (either with or external to nodemailer). #2

**Comment by salvozappa** [comment]
Closing since #2 is now merged. Thanks :+1:

**Comment by TheWebMachine** [comment]
It looks like the build is failing. What did I screw up? 😣

https://travis-ci.org/github/salvozappa/pipe-mail/builds/710876976

**Comment by TheWebMachine** [comment]
@sal-zappa, thoughts?
